# NORMALIZATION PROBLEM

In [16]:
import numpy as np

#Create a random 5x5 array and store it in variable X 
X = np.random.rand(5, 5) 

#Normalize the array using the formula 
X_normalized = (X - X.mean()) / X.std()

#Save the normalized ndarray as X_normalized.npy
np.save('div_by_3.npy', Div_by_3)

#Print the output of the original and normalized arrays
print("Original Array:\n", X, "\nNormalized Array:\n", X_normalized)

Original Array:
 [[0.16308214 0.31883791 0.97089049 0.61858942 0.96426956]
 [0.67146448 0.95398392 0.81408226 0.4207942  0.09930478]
 [0.62560672 0.51656225 0.29996069 0.23076427 0.6780331 ]
 [0.31896458 0.24110542 0.74231272 0.26688078 0.58554828]
 [0.41493015 0.93852747 0.00642389 0.56736883 0.38453586]] 
Normalized Array:
 [[-1.25561178 -0.6959337   1.64709059  0.38116512  1.62329955]
 [ 0.57116139  1.5863401   1.08363066 -0.32957357 -1.48478333]
 [ 0.40638043  0.0145503  -0.76376532 -1.01240919  0.59476444]
 [-0.69547852 -0.97525029  0.82574076 -0.88263152  0.2624382 ]
 [-0.35064488  1.53080034 -1.81853277  0.19711389 -0.45986089]]


# DIVISIBLE BY 3 PROBLEM

In [48]:
import numpy as np

#Create an array of the first 100 positive integers
n = np.arange(1,101)

#Square every element
A_squared = np.square(n)

#Resize into a 10x10 ndarray
A = A_squared.reshape(10,10)

#Determine the elements divisible by 3
Div_by_3 = A[A % 3 == 0]

#Save the result as div_by_3.npy
np.save('div_by_3.npy', Div_by_3)

#Print the output of "A" and "div_by_3"
print("A =\n", A, "\nElements divisible by 3:\n", Div_by_3)

A =
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 
Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
